[package]
name = "WASM-Algos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.92"
js-sys = "0.3.69"

[lib]
name = "algos"
crate-type = ["cdylib"]